import random
import time
import os

# Word pools for generative poetry
nouns = ["moon", "river", "forest", "dream", "fire", "cloud", "mountain", "echo", "shadow", "light"]
verbs = ["whispers", "dances", "flows", "shines", "fades", "rises", "falls", "wanders", "burns", "glows"]
adjectives = ["silent", "eternal", "fragile", "bright", "endless", "lonely", "ancient", "restless", "hidden", "wild"]

# ASCII art symbols
symbols = ["*", ".", "+", "~", "^", "o"]

def make_line():
    return f"The {random.choice(adjectives)} {random.choice(nouns)} {random.choice(verbs)}"

def haiku():
    return [make_line(), make_line(), make_line()]

def ascii_art(width=50, height=10):
    art = ""
    for _ in range(height):
        row = "".join(random.choice(symbols) for _ in range(width))
        art += row + "\n"
    return art

def show_poem_with_art():
    os.system("cls" if os.name == "nt" else "clear")
    art = ascii_art()
    poem = haiku()

    print("\033[95m" + art + "\033[0m")  # purple ASCII art
    print("\n\033[93m--- Digital Haiku ---\033[0m\n")
    for line in poem:
        print("\033[96m" + line + "\033[0m")
        time.sleep(1)  # dramatic pause
    print("\n" + "\033[92m~ generated by Nabajyoti)

if __name__ == "__main__":
    while True:
        show_poem_with_art()
        time.sleep(3)
