# ...existing code...
def show_poem_with_art():
    os.system("cls" if os.name == "nt" else "clear")
    art = ascii_art()
    poem = haiku()

    print("\033[95m" + art + "\033[0m")  # purple ASCII art
    print("\n\033[93m--- Digital Haiku ---\033[0m\n")
    for line in poem:
        print("\033[96m" + line + "\033[0m")
        time.sleep(1)  # dramatic pause
    print("\n" + "\033[92m~ generated by Nabajyoti\033[0m")
# ...existing code...
if __name__ == "__main__":
    try:
        while True:
            show_poem_with_art()
            time.sleep(3)
    except KeyboardInterrupt:
        print("\nExiting.")
# ...existing code...